# ======== SERVER CONFIG ==========
server.port=8080

# ======== DATABASE CONFIG (MariaDB 10.4.32) ==========
spring.datasource.url=jdbc:mariadb://localhost:3306/insa_complaints2?useUnicode=true&characterEncoding=utf8mb4
spring.datasource.username=root
spring.datasource.password=

spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# ======== JPA / HIBERNATE ==========
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDB103Dialect
spring.jpa.properties.hibernate.format_sql=true

# ======== JACKSON ==========
spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS=false

# ======== SECURITY ==========
spring.main.allow-circular-references=true

# JWT secret key
app.jwtSecret=MY_SECRET_KEY_123456789

# JWT expiration time (1 day)
app.jwtExpirationMs=86400000
